/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.23
 * Generated at: 2017-11-27 02:31:12 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class produtos_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1507994258446L));
    _jspx_dependants.put("jar:file:/C:/Users/VSIQUIERI/workspacePI/AdotaFacil_PIweb/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/PI/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153395882000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("<title>Adota Fácil</title>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("<link rel=\"icon\" href=\"imagens/icon.ico\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"estilos.css\">\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css?family=Muli\"\r\n");
      out.write("\trel=\"stylesheet\">\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css?family=Space+Mono\"\r\n");
      out.write("\trel=\"stylesheet\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css\">\r\n");
      out.write("\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\t<section class=\"cabecalho\">\r\n");
      out.write("\t\t");
      if (_jspx_meth_c_005fimport_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t</section>\r\n");
      out.write("\r\n");
      out.write("\t<div id=\"conteudo\" style=\"margin: 50px;\">\r\n");
      out.write("\t\t<div class=\"form-group row\">\r\n");
      out.write("\t\t\t<label for=\"filtro\" class=\"col-form-label col-sm-4\">Filtre\r\n");
      out.write("\t\t\t\tsua pesquisa:</label> <select id=\"filtro\" class=\"form-control col-sm-8\"\r\n");
      out.write("\t\t\t\tonchange=\"filtrar()\">\r\n");
      out.write("\t\t\t\t<option>Nenhum</option>\r\n");
      out.write("\t\t\t\t<option id=\"alfaCres\">Ordem Alfabética, crescente</option>\r\n");
      out.write("\t\t\t\t<option id=\"alfaDecres\">Ordem Alfabética, decrescente</option>\r\n");
      out.write("\t\t\t\t<option id=\"precoCres\">Preço, crescente</option>\r\n");
      out.write("\t\t\t\t<option id=\"precoDecres\">Preço, decrescente</option>\r\n");
      out.write("\t\t\t</select>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t<div id=\"produtos\">\r\n");
      out.write("\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t<div class=\"card col-sm-4\" style=\"width: 20rem;\" id=\"bone\"\r\n");
      out.write("\t\t\t\t\ttitle=\"20.00\">\r\n");
      out.write("\t\t\t\t\t<img class=\"card-img-top\" src=\"imagens/bone2.jpg\"\r\n");
      out.write("\t\t\t\t\t\talt=\"Card image cap\">\r\n");
      out.write("\t\t\t\t\t<div class=\"card-body\">\r\n");
      out.write("\t\t\t\t\t\t<h4 class=\"card-title\">Boné</h4>\r\n");
      out.write("\t\t\t\t\t\t<p class=\"card-text\">Boné Adota Fácil - R$20,00.</p>\r\n");
      out.write("\t\t\t\t\t\t<a href=\"bone.jsp\" class=\"btn btn-primary\">Detalhe</a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"card col-sm-4\" style=\"width: 20rem;\" id=\"caneta\"\r\n");
      out.write("\t\t\t\t\ttitle=\"10.00\">\r\n");
      out.write("\t\t\t\t\t<img class=\"card-img-top\" src=\"imagens/caneta.jpg\"\r\n");
      out.write("\t\t\t\t\t\talt=\"Card image cap\">\r\n");
      out.write("\t\t\t\t\t<div class=\"card-body\">\r\n");
      out.write("\t\t\t\t\t\t<h4 class=\"card-title\">Caneta</h4>\r\n");
      out.write("\t\t\t\t\t\t<p class=\"card-text\">Caneta Adota Fácil - R$10,00.</p>\r\n");
      out.write("\t\t\t\t\t\t<a href=\"caneta.jsp\" class=\"btn btn-primary\">Detalhe</a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"card col-md-4\" style=\"width: 20rem;\" id=\"camiseta\"\r\n");
      out.write("\t\t\t\t\ttitle=\"49.99\">\r\n");
      out.write("\t\t\t\t\t<img class=\"card-img-top\" src=\"imagens/camiseta.jpg\"\r\n");
      out.write("\t\t\t\t\t\talt=\"Card image cap\">\r\n");
      out.write("\t\t\t\t\t<div class=\"card-body\">\r\n");
      out.write("\t\t\t\t\t\t<h4 class=\"card-title\">Camiseta</h4>\r\n");
      out.write("\t\t\t\t\t\t<p class=\"card-text\">Camiseta Adota Fácil - R$49,99.</p>\r\n");
      out.write("\t\t\t\t\t\t<a href=\"camiseta.jsp\" class=\"btn btn-primary\">Detalhe</a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"card col-md-4\" style=\"width: 20rem;\" id=\"caneca\"\r\n");
      out.write("\t\t\t\t\ttitle=\"49.90\">\r\n");
      out.write("\t\t\t\t\t<img class=\"card-img-top\" src=\"imagens/caneca.jpg\"\r\n");
      out.write("\t\t\t\t\t\talt=\"Card image cap\">\r\n");
      out.write("\t\t\t\t\t<div class=\"card-body\">\r\n");
      out.write("\t\t\t\t\t\t<h4 class=\"card-title\">Caneca</h4>\r\n");
      out.write("\t\t\t\t\t\t<p class=\"card-text\">Caneca Adota Fácil - R$49,90.</p>\r\n");
      out.write("\t\t\t\t\t\t<a href=\"caneca.jsp\" class=\"btn btn-primary\">Detalhe</a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"card col-md-4\" style=\"width: 20rem;\" id=\"copo\"\r\n");
      out.write("\t\t\t\t\ttitle=\"15.00\">\r\n");
      out.write("\t\t\t\t\t<img class=\"card-img-top\" src=\"imagens/copo.jpg\"\r\n");
      out.write("\t\t\t\t\t\talt=\"Card image cap\">\r\n");
      out.write("\t\t\t\t\t<div class=\"card-body\">\r\n");
      out.write("\t\t\t\t\t\t<h4 class=\"card-title\">Copo</h4>\r\n");
      out.write("\t\t\t\t\t\t<p class=\"card-text\">Copo Adota Fácil - R$15,00.</p>\r\n");
      out.write("\t\t\t\t\t\t<a href=\"copoU.jsp\" class=\"btn btn-primary\">Detalhe</a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<script src=\"https://code.jquery.com/jquery-3.2.1.slim.min.js\"></script>\r\n");
      out.write("\t<script\r\n");
      out.write("\t\tsrc=\"https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js\"></script>\r\n");
      out.write("\t<script\r\n");
      out.write("\t\tsrc=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\tfunction getSelectTxt(elementId) {\r\n");
      out.write("\r\n");
      out.write("\t\t\tvar val = document.getElementById(elementId);\r\n");
      out.write("\r\n");
      out.write("\t\t\tif (val.selectedIndex === -1)\r\n");
      out.write("\t\t\t\treturn null;\r\n");
      out.write("\r\n");
      out.write("\t\t\treturn val.selectedIndex;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tfunction filtrar() {\r\n");
      out.write("\t\t\tif (getSelectTxt(\"filtro\") === 1) {\r\n");
      out.write("\t\t\t\t$(\".row .card\").sort(function(a, b) {\r\n");
      out.write("\t\t\t\t\treturn a.id >= b.id;\r\n");
      out.write("\t\t\t\t}).each(function() {\r\n");
      out.write("\t\t\t\t\tvar elem = $(this);\r\n");
      out.write("\t\t\t\t\telem.remove();\r\n");
      out.write("\t\t\t\t\t$(elem).appendTo(\".row\");\r\n");
      out.write("\t\t\t\t\telem.remove();\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t} else if (getSelectTxt(\"filtro\") === 2) {\r\n");
      out.write("\t\t\t\t$(\".row .card\").sort(function(a, b) {\r\n");
      out.write("\t\t\t\t\treturn a.id <= b.id;\r\n");
      out.write("\t\t\t\t}).each(function() {\r\n");
      out.write("\t\t\t\t\tvar elem = $(this);\r\n");
      out.write("\t\t\t\t\telem.remove();\r\n");
      out.write("\t\t\t\t\t$(elem).appendTo(\".row\");\r\n");
      out.write("\t\t\t\t\telem.remove();\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t} else if (getSelectTxt(\"filtro\") === 3) {\r\n");
      out.write("\t\t\t\t$(\".row .card\").sort(function(a, b) {\r\n");
      out.write("\t\t\t\t\tvar x = Number(a.title.replace(/[^0-9\\.-]+/g, \"\"));\r\n");
      out.write("\t\t\t\t\tvar y = Number(b.title.replace(/[^0-9\\.-]+/g, \"\"));\r\n");
      out.write("\t\t\t\t\treturn x >= y;\r\n");
      out.write("\t\t\t\t}).each(function() {\r\n");
      out.write("\t\t\t\t\tvar elem = $(this);\r\n");
      out.write("\t\t\t\t\telem.remove();\r\n");
      out.write("\t\t\t\t\t$(elem).appendTo(\".row\");\r\n");
      out.write("\t\t\t\t\telem.remove();\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t} else if (getSelectTxt(\"filtro\") === 4) {\r\n");
      out.write("\t\t\t\t$(\".row .card\").sort(function(a, b) {\r\n");
      out.write("\t\t\t\t\tvar x = Number(a.title.replace(/[^0-9\\.-]+/g, \"\"));\r\n");
      out.write("\t\t\t\t\tvar y = Number(b.title.replace(/[^0-9\\.-]+/g, \"\"));\r\n");
      out.write("\t\t\t\t\treturn x <= y;\r\n");
      out.write("\t\t\t\t}).each(function() {\r\n");
      out.write("\t\t\t\t\tvar elem = $(this);\r\n");
      out.write("\t\t\t\t\telem.remove();\r\n");
      out.write("\t\t\t\t\t$(elem).appendTo(\".row\");\r\n");
      out.write("\t\t\t\t\telem.remove();\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t</script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fimport_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:import
    org.apache.taglibs.standard.tag.rt.core.ImportTag _jspx_th_c_005fimport_005f0 = (org.apache.taglibs.standard.tag.rt.core.ImportTag) _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.ImportTag.class);
    boolean _jspx_th_c_005fimport_005f0_reused = false;
    try {
      _jspx_th_c_005fimport_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fimport_005f0.setParent(null);
      // /produtos.jsp(27,2) name = url type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fimport_005f0.setUrl("cabecalho.jsp");
      int[] _jspx_push_body_count_c_005fimport_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fimport_005f0 = _jspx_th_c_005fimport_005f0.doStartTag();
        if (_jspx_th_c_005fimport_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fimport_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fimport_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fimport_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody.reuse(_jspx_th_c_005fimport_005f0);
      _jspx_th_c_005fimport_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fimport_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fimport_005f0_reused);
    }
    return false;
  }
}
